### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by s338523764** [s338523764/markdown-portfolio#2]
- [x] Turn on GitHub Pages
- [x] Outline my portfolio
- [ ] Introduce myself to the world

**Comment by s338523764** [comment]
- [ ] done
